import 'dart:io';
import 'dart:math';
import 'package:awesome_snackbar_content/awesome_snackbar_content.dart';
import 'package:camera/camera.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gallery_saver/gallery_saver.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:online_class/presentation/bloc/news_search/news_search_bloc.dart';
import 'package:online_class/shared/shared.dart';
import 'package:provider/provider.dart';
import 'package:supercharged/supercharged.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart' as pPath;

import '../../../data/api/api_services.dart';
import '../../../data/models/models.dart';
import '../../../providerr/providers.dart';
import '../../widgets/widgets.dart';

part 'login_page.dart';
part 'general_pages.dart';
part 'online_page.dart';
part 'food_details_page.dart';
part 'maem.dart';
part 'home_screen.dart';
part 'article.dart';
part 'detail_article.dart';
part 'web_view_detail.dart';
part 'news_list_page.dart';
part 'news_search.dart';
part 'news_search_list_page.dart';
part 'load_image_screen.dart';
